import { z } from "zod"
import { PROMPT_PRESET_NAMES } from "@/engine/prompt-presets"

const NAME_PATTERN = /^[a-z][a-z0-9_-]*$/

const safeName = z.string().min(1).regex(NAME_PATTERN, "must match ^[a-z][a-z0-9_-]*$")

const ackIconsSchema = z
  .object({
    progress: z.string().default("hourglass_flowing_sand"),
    success: z.string().default("white_check_mark"),
    error: z.string().default("x"),
  })
  .default({
    progress: "hourglass_flowing_sand",
    success: "white_check_mark",
    error: "x",
  })

const slackChannelSchema = z.object({
  id: z.uuid(),
  name: safeName,
  type: z.literal("slack"),
  enabled: z.boolean().default(true),
  botToken: z.string().default(""),
  appToken: z.string().default(""),
  /**
   * When the bot adds the in-progress / done / error reactions to the
   * incoming message:
   *   - "off": never (codex is fully responsible for any visible feedback)
   *   - "mention": only when the bot is @-mentioned (default)
   *   - "always": every accepted message event
   * Reaction events themselves never trigger ack — they are silent regardless.
   */
  ackMode: z.enum(["off", "mention", "always"]).default("mention"),
  /** Override the emoji names used by the ack reactions. Slack reaction names without `:`. */
  ackIcons: ackIconsSchema,
})

/**
 * One scheduled prompt. `runAt` is either an ISO 8601 timestamp (one-shot)
 * or a 5-field cron expression (recurring) — discriminated at parse time by
 * whether the string contains whitespace. One-shot entries are removed from
 * settings.json after they fire; cron entries persist and re-fire forever.
 */
const scheduleEntrySchema = z.object({
  id: z.uuid(),
  name: safeName,
  runAt: z.string().min(1),
  prompt: z.string().min(1),
  enabled: z.boolean().default(true),
})

const scheduleChannelSchema = z.object({
  id: z.uuid(),
  name: safeName,
  type: z.literal("schedule"),
  enabled: z.boolean().default(true),
  entries: z.array(scheduleEntrySchema).default([]),
})

const channelSchema = z.discriminatedUnion("type", [slackChannelSchema, scheduleChannelSchema])

const agentSchema = z.object({
  name: safeName,
  enabled: z.boolean().default(true),
  /**
   * Codex `thread/start` id this agent uses across every channel and turn.
   * Set the first time the agent runs; reused via `thread/resume` afterward.
   * Absent until the first turn fires.
   */
  codexThreadId: z.string().min(1).optional(),
  /**
   * When true (default) leuco prepends a built-in dynamic preamble to the
   * agent's `developer_instructions` covering the bot's own Slack identity,
   * loop avoidance, sub-agent paths, and self-edit guidance. Set to false to
   * pass the per-agent TOML instructions through verbatim.
   */
  useCommonInstructions: z.boolean().default(true),
  /**
   * Named system-prompt presets to splice in between the dynamic preamble and
   * the per-agent TOML text. Names are validated against the registered set
   * in `lib/engine/prompt-presets.ts`. Defaults to `["friendly"]` so a fresh
   * agent has a usable Slack persona without extra configuration; pass an
   * empty array to opt out.
   */
  prompts: z.array(z.enum(PROMPT_PRESET_NAMES)).default(["friendly"]),
  channels: z.array(channelSchema).default([]),
})

export const projectSchema = z.object({
  /**
   * Stable per-project identifier. The on-disk directory at
   * `~/.leuco/projects/<id>/` is keyed by this id, not by `name`, so renames
   * are a single field write and same-name projects (different repos with
   * matching basenames) can coexist. UUIDs are generated by `projects add` /
   * `projects create`; legacy installs without an id are migrated on first
   * load by `LeucoProjectStore.list`.
   */
  id: z.uuid(),
  name: safeName,
  path: z.string().min(1),
  agents: z.array(agentSchema).default([]),
})

export type Channel = z.infer<typeof channelSchema>
export type SlackChannel = z.infer<typeof slackChannelSchema>
export type ScheduleChannel = z.infer<typeof scheduleChannelSchema>
export type ScheduleEntry = z.infer<typeof scheduleEntrySchema>
export type Agent = z.infer<typeof agentSchema>
export type Project = z.infer<typeof projectSchema>
