import { isAbsolute } from "node:path"
import { z } from "zod"
import { PROMPT_PRESET_NAMES, PromptPreset } from "@/engine/prompt-presets"

const NAME_PATTERN = /^[a-z][a-z0-9_-]*$/

const safeName = z.string().min(1).regex(NAME_PATTERN, "must match ^[a-z][a-z0-9_-]*$")

const ackIconsSchema = z
  .object({
    progress: z.string().default("hourglass_flowing_sand"),
    success: z.string().default("white_check_mark"),
    error: z.string().default("x"),
  })
  .default({
    progress: "hourglass_flowing_sand",
    success: "white_check_mark",
    error: "x",
  })

const slackChannelSchema = z.object({
  id: z.uuid(),
  name: safeName,
  type: z.literal("slack"),
  enabled: z.boolean().default(true),
  botToken: z.string().default(""),
  appToken: z.string().default(""),
  /**
   * When the bot adds the in-progress / done / error reactions to the
   * incoming message:
   *   - "off": never (codex is fully responsible for any visible feedback)
   *   - "mention": only when the bot is @-mentioned
   *   - "always": every accepted message event
   * Reaction events themselves never trigger ack — they are silent regardless.
   */
  ackMode: z.enum(["off", "mention", "always"]).default("off"),
  /** Override the emoji names used by the ack reactions. Slack reaction names without `:`. */
  ackIcons: ackIconsSchema,
})

/**
 * One scheduled prompt. `runAt` is either an ISO 8601 timestamp (one-shot)
 * or a 5-field cron expression (recurring) — discriminated at parse time by
 * whether the string contains whitespace. One-shot entries are removed from
 * settings.json after they fire; cron entries persist and re-fire forever.
 */
const scheduleEntrySchema = z.object({
  id: z.uuid(),
  name: safeName,
  runAt: z.string().min(1),
  prompt: z.string().min(1),
  enabled: z.boolean().default(true),
})

const scheduleChannelSchema = z.object({
  id: z.uuid(),
  name: safeName,
  type: z.literal("schedule"),
  enabled: z.boolean().default(true),
  entries: z.array(scheduleEntrySchema).default([]),
})

const channelSchema = z.discriminatedUnion("type", [slackChannelSchema, scheduleChannelSchema])

/**
 * One extra stdio MCP server to attach to this project's codex, on top of the
 * built-in `leuco` server. leuco stays agnostic about what the server does:
 * it only forwards `command`/`args`/`env` verbatim into the tenant's
 * CODEX_HOME `config.toml` as a `[mcp_servers.<key>]` block. Per-project `env`
 * is how callers scope a shared MCP binary to a specific identity (e.g. a
 * token-vault MCP keyed by the owner's email), without leuco needing to model
 * that identity itself.
 */
const mcpServerSchema = z.object({
  command: z.string().min(1),
  args: z.array(z.string()).default([]),
  // Keys become bare TOML keys in the tenant's config.toml inline `env`
  // table — an unconstrained key (spaces, `=`, newlines) would corrupt the
  // file and silently break the tenant's codex start.
  env: z
    .record(
      z
        .string()
        .regex(/^[A-Za-z_][A-Za-z0-9_]*$/, "must be an env var name ([A-Za-z_][A-Za-z0-9_]*)"),
      z.string(),
    )
    .default({}),
})

/**
 * Schema version for forward-compatible migration. Absent in pre-0.9
 * installs; `loadOrMigrate` treats missing version as v1 and upgrades.
 */
const CURRENT_SCHEMA_VERSION = 2

const projectStateSchema = z
  .object({
    codexThreadId: z.string().min(1).nullable().default(null),
    scheduleLastFiredAt: z.record(z.string(), z.number()).default({}),
  })
  .default({ codexThreadId: null, scheduleLastFiredAt: {} })

export const projectSchema = z.object({
  version: z.number().int().default(CURRENT_SCHEMA_VERSION),
  /**
   * Stable per-project identifier. The on-disk directory at
   * `~/.leuco/projects/<id>/` is keyed by this id, not by `name`, so renames
   * are a single field write and same-name projects (different repos with
   * matching basenames) can coexist. UUIDs are generated by `projects add` /
   * `projects create`; legacy installs without an id are migrated on first
   * load by `LeucoProjectStore.list`.
   */
  id: z.uuid(),
  name: safeName,
  // Project path must be absolute. It becomes codex's `cwd` and is also
  // written into the tenant's `config.toml` as `[projects.<path>]
  // trust_level = "trusted"` — granting "trusted" to a relative path would
  // be path-dependent and surprising. CLI handlers already `resolve()` user
  // input; this guard catches hand-edited settings.json.
  path: z.string().min(1).refine(isAbsolute, "must be an absolute path"),
  enabled: z.boolean().default(true),
  useCommonInstructions: z.boolean().default(true),
  /** Optional codex model override passed to `thread/start`. null = codex default. */
  model: z.string().min(1).nullable().default(null),
  /** Optional per-project instructions appended after the preamble and presets. */
  developerInstructions: z.string().min(1).nullable().default(null),
  prompts: z
    .array(z.enum(PROMPT_PRESET_NAMES))
    .default([PromptPreset.CORE, PromptPreset.COMMUNICATION, PromptPreset.COMMUNICATION_SLACK]),
  channels: z.array(channelSchema).default([]),
  mcpServers: z.record(safeName, mcpServerSchema).default({}),
  state: projectStateSchema,
})

export { CURRENT_SCHEMA_VERSION }

export type Channel = z.infer<typeof channelSchema>
export type SlackChannel = z.infer<typeof slackChannelSchema>
export type ScheduleChannel = z.infer<typeof scheduleChannelSchema>
export type ScheduleEntry = z.infer<typeof scheduleEntrySchema>
export type McpServer = z.infer<typeof mcpServerSchema>
export type ProjectState = z.infer<typeof projectStateSchema>
export type Project = z.infer<typeof projectSchema>

export const EMPTY_PROJECT_STATE: ProjectState = { codexThreadId: null, scheduleLastFiredAt: {} }
